builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin    # 只构建 macOS 版本
    goarch:
      - arm64    # 添加 arm64 架构支持
      - amd64    # 保留 Intel 架构支持
    ignore:
      - goos: darwin
        goarch: 386    # 移除不需要的架构组合

archives:
  - replacements:
      darwin: macOS    # 更改显示名称
      amd64: x86_64
      arm64: arm64    # 添加 ARM 架构的显示名称

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  header: |
    ## Hi! 欢迎使用HDU-CLI ({{ .Date }})

    此处是版本介绍

  footer: |
    ## 感谢您的支持!

    以上就是在 {{ .Tag }} 上的改动!
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

nfpms:
  - id: packages
    replacements:
      amd64: 64-bit
      arm64: arm64    # 添加 ARM 架构的替换名称
      darwin: macOS

    vendor: HDUHELP
    homepage: https://github.com/hduhelp/hdu-cli
    maintainer: HDUHELP
    license: Apache 2.0
    formats:
      - deb
      - rpm

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/{{ .Env.FURY_USER_NAME }}/
